# must do before using this action:
# - set up RELEASE_TOKEN in secrets of the repository avocado-framework/avocado
# - set up RTD_TOKEN in secrets to update readthedocs
# - set up two tokens for twine: PYPI_USER and PYPI_PASSWD

name: Release tests
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '0.0'
      devel_name:
        description: 'Developer Name'
        required: true
        default: 'Avocado Developer'
      devel_mail:
        description: 'Developer mail'
        required: true
        default: 'avocado@redhat.com'
      rtd_project:
        description: 'readthedocs project name'
        required: true
        default: 'avocado-framework'

jobs:
  build-and-publish-eggs:
    name: Build eggs and publish them
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.11.1]
      fail-fast: false

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c
        with:
          app_id: ${{ secrets.MR_AVOCADO_ID }}
          installation_id: ${{ secrets.MR_AVOCADO_INSTALLATION_ID }}
          private_key: ${{ secrets.MR_AVOCADO_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.event.inputs.version }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build eggs
        run: |
          if python -c 'import sys; exit(0) if sys.version_info.minor > 11 else exit(1)' ; then
            pip install setuptools
          fi
          make -f Makefile.gh build-egg
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ steps.generate_token.outputs.token }}
          file: ${{ github.workspace }}/EGG_UPLOAD/avocado_framework*egg
          tag: ${{ github.event.inputs.version }}
          overwrite: true
          file_glob: true
